// netlify/functions/server.js
import { createRequestHandler } from "@remix-run/netlify";

// Import the server build generated by Remix at the path defined in remix.config.js
import * as build from "./server/build.js"; // Path relative to this file

export const handler = createRequestHandler({
  build,
  mode: process.env.NODE_ENV,
  // getLoadContext can be used to pass data/functions to loaders/actions
  getLoadContext: () => ({}),
});
