// netlify/functions/server.js
// Uses the Netlify adapter from the reinstalled v1 package
import { createRequestHandler } from "@remix-run/netlify";

// Import the virtual module generated by Remix build
// IMPORTANT: Ensure this path is correct based on your build output structure.
// It might be relative to this file or use an alias defined during build.
// If using default Remix v2 structure, this import might need adjustment
// or might be handled differently by the older adapter.
// Use relative path to the actual server build output for v1 adapter
import * as build from "../../build/server/index.js";

export const handler = createRequestHandler({
  build,
  // getLoadContext can be used to pass data/functions to loaders/actions
  // Example: return { netlifyEdgeContext: context };
  getLoadContext: () => ({}),
});
